#!/bin/sh

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local oid> <remote ref> <remote oid>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

# get the path to this script file
DIR=$(dirname "$0")
user_name=$(git config user.name)
ECHO $user_name
if [[ "$user_name" == "BigBern44" || "$user_name" == "geo-n13" ]]; then
  # Verifie si le nom d'utilisateur git est égal a BigBern44 ou geo-n13
  exit 0
else
  # Sinon empeche le push
  echo "Nom d'utilisateur incorrect"
  exit 1
fi

# Java >= 11
exec java $DIR/PrePush.java "$@"

